"""
Small helper to append feedback rows to a Google Sheet using a local OAuth token

Expect a `secrets/token.pickle` generated by `scripts/get_gsheet_token.py` and
`secrets/credentials.json` (the OAuth client) next to it.

This module exposes `append_feedback_row(dict)` which accepts a row dict with
keys: timestamp, username, email, prompt, response, rating, comment, fallback
"""
from pathlib import Path
import pickle
import time
import logging
from typing import Dict, Iterable
from datetime import datetime

import gspread
from google.auth.transport.requests import Request

LOG = logging.getLogger(__name__)

ROOT = Path(__file__).resolve().parent
SECRETS = ROOT / "secrets"
TOKEN_PATH = SECRETS / "token.pickle"
CREDENTIALS_PATH = SECRETS / "credentials.json"

SHEET_ID = None  # set via env or override before use

# Column headers for the feedback sheet
HEADERS = [
    "Timestamp",
    "User",
    "Email",
    "Prompt",
    "Bot Response",
    "Rating",
    "Comment",
    "Fallback"
]


def _get_gspread_client():
    if not TOKEN_PATH.exists():
        raise RuntimeError(f"Missing token file at {TOKEN_PATH}. Run scripts/get_gsheet_token.py first")
    with open(TOKEN_PATH, "rb") as f:
        creds = pickle.load(f)

    if getattr(creds, "expired", False) and getattr(creds, "refresh_token", None):
        try:
            creds.refresh(Request())
            with open(TOKEN_PATH, "wb") as f:
                pickle.dump(creds, f)
        except Exception:
            LOG.exception("Failed to refresh credentials")

    return gspread.authorize(creds)


def _ensure_headers(ws):
    """Create headers if the sheet is empty."""
    try:
        first_row = ws.row_values(1)
        if not first_row or len(first_row) == 0:
            ws.insert_row(HEADERS, index=1)
            LOG.info("Sheet headers created")
    except Exception as e:
        LOG.warning("Could not check/create headers: %s", e)


def append_feedback_row(row: Dict[str, object], sheet_id: str | None = None):
    """Append a single row to the sheet with proper formatting."""
    sheet_key = sheet_id or SHEET_ID
    if not sheet_key:
        raise RuntimeError("SHEET_ID is not configured. Provide sheet_id argument or set gsheets_feedback.SHEET_ID")

    client = _get_gspread_client()
    sh = client.open_by_key(sheet_key)
    ws = sh.sheet1

    # Ensure headers exist
    _ensure_headers(ws)

    # Format timestamp as readable datetime
    ts = row.get("timestamp", int(time.time()))
    if isinstance(ts, (int, float)):
        ts_str = datetime.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M:%S")
    else:
        ts_str = str(ts)

    values = [
        ts_str,
        row.get("username", ""),
        row.get("email", ""),
        row.get("prompt", ""),
        row.get("response", ""),
        row.get("rating", ""),
        row.get("comment", ""),
        str(row.get("fallback", False)),
    ]
    ws.append_row(values, value_input_option="USER_ENTERED")
    LOG.info("Feedback row appended to sheet")


def append_feedback_rows(rows: Iterable[Dict[str, object]], sheet_id: str | None = None):
    for r in rows:
        append_feedback_row(r, sheet_id=sheet_id)
